name: Books App Workflow
on:
  pull_request:
    types:
      - opened
    branches:
      - main
      - 'dev-test'
      - 'devs-**'
  push:
    branches:
      - main
      - 'dev-**'
      - 'dev/**/'
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Get the Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/node-setup@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Start App
        run: echo "App Starting ....."




